version: "3.7"

services:
  app:
    build:
      context: .
    env_file: .env
    volumes:
      - ./src:/opt/app/src:delegated
      - ./requirements.txt:/opt/app/requirements.txt
      - ./firebase.json:/opt/app/firebase.json

volumes:
    notused:
