################################################
############# Configurações do Bot #############
################################################

# Ativar modo DEBUG
DEBUG: true

TELEGRAM:
    # Telegram bot token
    # Pode ser conseguido conversando com BotFather (https://telegram.me/BotFather): /newbot, /token
    TOKEN: "token"

FIREBASE:
    API_KEY: "API_KEY"
    AUTH_DOMAIN: "projectId.firebaseapp.com"
    DATA_BASE_URL: "https://projectId.firebaseio.com"
    STORAGE_BUCKET: "projectId.appspot.com"
    SERVICE_ACCOUNT: "./firebase.json"

# Columna "TZ": https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
TIMEZONE: "America/Recife"

################################################
############# Configurações do Racha ###########
################################################


RACHA:
    # Group id
    GROUP_ID: "GROUP_ID"

    # Número de times
    MAX_TEAMS: 4

    # Número de jogadores por time
    MAX_NUMBER_PLAYERS_TEAM: 6

    # Cores usadas nos times
    TEAMS_COLORS: ["Azul", "Vermelho", "Verde", "Branco"]

    # Se jogador não tiver rating, bot usa DEFAULT_RATING
    DEFAULT_RATING: 3.00

    # Quando o bot calcula os times, para cada jogador um número entre o range abaixo é somado ao rating do jogador
    RATING_RANGE_VARIATION: [-0.25, 0.25]

    # Se OPEN_CHECK_IN_DATE for definido, o bot irá automaticamente abrir o check in do racha.
    OPEN_CHECK_IN_DATE: monday 20:00

    # Se CLOSE_CHECK_IN_DATE for definido, o bot irá automaticamente fechar o check in do racha.
    CLOSE_CHECK_IN_DATE: tuesday 15:00
