################################################
############# Configurações do Bot #############
################################################

# O bot sempre vai permitir os comandos desse usuário
MASTER_ADMIN_TELEGRAM_ID: 1234567890

TELEGRAM:
    # Group id
    GROUP_ID: 1234567890

    # Telegram bot token
    # Pode ser conseguido conversando com BotFather (https://telegram.me/BotFather): /newbot, /token
    TOKEN: "token"

FIREBASE:
    API_KEY: "API_KEY"
    AUTH_DOMAIN: "projectId.firebaseapp.com"
    DATA_BASE_URL: "https://projectId.firebaseio.com"
    STORAGE_BUCKET: "projectId.appspot.com"
    SERVICE_ACCOUNT: "./firebase.json"


################################################
############# Configurações do Racha ###########
################################################

RACHA:
    # Número de times
    MAX_TEAMS: 4

    # Número de jogadores por time
    MAX_NUMBER_PLAYERS_TEAM: 6

    # Cores usadas nos times
    TEAMS_COLORS: ["Azul", "Vermelho", "Verde", "Branco"]

    # Se OPEN_CHECK_IN_DATE for definido, o bot irá automaticamente abrir o check in do racha.
    OPEN_CHECK_IN_DATE: monday 20:00

    # Se CLOSE_CHECK_IN_DATE for definido, o bot irá automaticamente fechar o check in do racha.
    CLOSE_CHECK_IN_DATE: tuesday 15:00
