#! /bin/bash

set -x
set -e

cp stack-overgol-bot.service /lib/systemd/system/

chmod 644 /lib/systemd/system/stack-overgol-bot.service

systemctl daemon-reload

systemctl enable stack-overgol-bot.service

echo "DONE"
