version: 2

jobs:
  publish_image_to_docker_hub:
    docker:
      - image: docker:18
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Log in to Docker Hub
          command: echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
      - run:
          name: Build Docker image
          command: docker build -t matheussampaio/stack-overgol:latest .
      - run:
          name: Push Docker image to Docker Hub
          command: docker push matheussampaio/stack-overgol:latest

workflows:
  version: 2
  continuous_integration:
    jobs:
      - publish_image_to_docker_hub:
          filters:
            branches:
              only:
                - master
