version: 2

jobs:
  test:
    docker:
      - image: docker:18
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t matheussampaio/stack-overgol .
      - run:
          name: Run tests
          command: docker run matheussampaio/stack-overgol nose2

  publish_image_to_docker_hub:
    docker:
      - image: docker:18
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Log in to Docker Hub
          command: echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
      - run:
          name: Build Docker image
          command: docker build -t matheussampaio/stack-overgol:${CIRCLE_SHA1} .
      - run:
          name: Push Docker image to Docker Hub
          command: docker push matheussampaio/stack-overgol

workflows:
  version: 2
  continuous_integration:
    jobs:
      - test

      - publish_image_to_docker_hub:
          requires:
            - test
          filters:
            branches:
              only:
                - master
